name: Build

on:
  push:
    branches:
      - florian
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: send vps
        run: |
          scp -r * vps:/var/www/html
